services:
  league_predictor:
    build: .
    container_name: league_predictor
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes: # can be removed in prod
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - RIOT_API_KEY=${RIOT_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"